export const endpoints = {
  users: "/users",
  movies: "/movies",
  locations: "/location",
  showtimes: "/showtimes",
  snacks: "/snacks",
  snackById: (id: string | number) => `/snacks/${id}`,
  snacksByCategory: (category: string) => `/snacks?category=${encodeURIComponent(category)}`,
  availableSnacks: "/snacks?isAvailable=true",
  seatsByShowtime: (showtimeId: string) => `/seats/${showtimeId}`,
  movieById: (id: string | number) => `/movies/${id}`,
  showtimeById: (id: string | number) => `/showtimes/${id}`,
  userWithRoles: "/users?_expand=role",
  userById: (id: string | number) => `/users/${id}`,
  usersByEmail: (email: string) => `/users?email=${encodeURIComponent(email)}`,
} as const;
