export const endpoints = {
  users: "/users",
  movies: "/movies",
  countries: "/countries",
  cities: "/cities",
  cinemas: "/cinemas",
  rooms: "/rooms",
  roomById: (id: string | number) => `/rooms/${id}`,
  tickets: "/tickets",
  ticketsByUser: (userId: string | number) => `/tickets?userId=${userId}`,
  showtimes: "/showtimes",
  snacks: "/snacks",
  snackById: (id: string | number) => `/snacks/${id}`,
  snacksByCategory: (category: string) => `/snacks?category=${encodeURIComponent(category)}`,
  availableSnacks: "/snacks?isAvailable=true",
  membershipBenefits: "/membershipBenefits",
  membershipBenefitById: (id: string | number) => `/membershipBenefits/${id}`,
  movieById: (id: string | number) => `/movies/${id}`,
  showtimeById: (id: string | number) => `/showtimes/${id}`,
  userWithRoles: "/users?_expand=role",
  userById: (id: string | number) => `/users/${id}`,
  usersByEmail: (email: string) => `/users?email=${encodeURIComponent(email)}`,
} as const;
